### ISSUE TITLE
/setup.sh: line 28: wget: command not found

### ISSUE THREAD

**Issue by Ge0** [bodenr/docker-devstack#3]
When building the image, we get this error:

```
Step 9 : RUN /setup.sh
[...]
/setup.sh: line 28: wget: command not found
```

The solution is simply to add wget to the packages to install.

**Comment by bodenr** [comment]
@Ge0 sorry, but I'm not supporting this project.
As indicated in the README it was just a toy.

**Comment by Ge0** [comment]
No problem, will start a project on my own, then!

Thank you for your quick reply.
